### ISSUE TITLE
How to add new entries?

### ISSUE THREAD

**Issue by fingolfin** [thosgood/maths-dictionary#36]
Suppose I want to add a new entry (say for the two meanings of "lattice", or for the alternate meaning of limit at <https://www.wikidata.org/wiki/Q177239>).

How would I go about that? I saw a tool `bin/new_entry` and it produced an entry on the clipboard. But it was in the old format. Also, formatted completely differently from existing entries. Finally, where do I put it -- just anywhere into the JSON file?

**Comment by thosgood** [comment]
I've just updated (https://github.com/thosgood/maths-dictionary/commit/0c95a5a681b7f9b94afef8c82af9557dd57ae062) the `bin/new_entry` tool to work with the new format — it's true that it looks different from the current entries in `nouns.json` but this doesn't matter, since everything gets run through a JSON prettifier at some point anyway.

It's similar for where you insert it into the JSON file: the file will get auto-sorted when prettified, so it's probably easiest to simply add them at the very end.

These are all good questions, but basically you're the first person to ask about adding new entries rather than just translating existing ones, so I haven't really written any documentation for this yet. Thanks for your patience!

**Comment by thosgood** [comment]
just to be clear: if you want to paste the output of the `new_entry` tool into `nouns.json` then you'll need to make sure to add a comma after the penultimate closing brace (on the penultimate line) and then paste your entry directly after this on a new line

this is rather annoying, and it's one of the reasons I need to build an actual front-end for this, rather than just editing a JSON file manually

**Comment by fingolfin** [comment]
Yeah, JSON isn't actually great for hand-editing by humans :-/. But it's not problem for me, really, I just am trying to get my bearing. Your answer helps a lot!

So, which tool do you use for formatting and sorting? Then I can do that and make a PR with the formatting and sorting already applied.

**Comment by thosgood** [comment]
I have a plugin for my text editor (Sublime Text) that does this, but I think any of the JSON validators/formatters that you can find on the internet all give identical outputs
